language: ruby
rvm:
  - 2.1.8
  - 2.2.4
matrix:
  allow_failures:
    - rvm: 2.1.8
env:
  - DB=postgresql
addons:
  postgresql: "9.3"
script:
  - RAILS_ENV=test bundle exec rake db:setup --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
before_script:
  - cp config/secrets.yml.travis config/secrets.yml
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database filentoryTEST;' -U postgres
