language: ruby
rvm:
  - 2.1.2
env:
  - DB=postgresql
addons:
  postgresql: "9.3"
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/secrets.yml.travis config/secrets.yml
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database filentoryTEST;' -U postgres
