language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.6
  - 2.7.1
matrix:
  allow_failures:
    - rvm: 2.3.8
    - rvm: 2.4.5
services:
  - postgresql
env:
  - DB=postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
script:
  - RAILS_ENV=test bundle exec rake db:setup --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake
before_script:
  - cp config/secrets.yml.travis config/secrets.yml
  - cp config/database.yml.travis config/database.yml
  - gem update --system
  - psql -c 'create database filentoryTEST;' -U postgres
